#
###################################
# Site wide configuration
####################################
#
title: Chennai Astronomy Club
email: chennaiastronomyclub@gmail.com
description: This is an effort to bring together all the astronomy and science lovers of Chennai and anywhere outside. 
# the base hostname & protocol for your site
# If your project is placed in https://github.com/yourname/yourname.github.io at master branch
# Then, the 'url' is: http://yourname.github.io
# If your project is placed in another repository as a gh-pages branch, like: https://github.com/yourname/projectname
# Then, the 'url' is: http://yourname.github.io/projectname
url: 

#
###################################
# Jekyll configuration
####################################
#
markdown:    kramdown
highlighter:  pygments
excerpt_separator: <!--more-->

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Chennai Astronomy Club
  avatar: avatar.jpg
  job: "We are stardust"
  bio: "This is an effort to bring together all the astronomy and science lovers of Chennai. We regularly organise star parties, outreach events and meetups."
  email: chennaiastronomyclub@gmail.com
  disqus-shortname: ChennaiAstronomyClub
  twitter: cacastronomers
  facebook: ChennaiAstronomyClub
  github: chennaiastronomyclub